#!/usr/bin/python3

import sys
import json
import struct

import dbus
from dbus.mainloop.glib import DBusGMainLoop
from gi.repository import GLib

def handle_theme(theme):
  # 1 -> dark, 2 -> light
  if theme == 1:
    kind = 'dark'
  else:
    kind = 'light'
  msg = {'theme': kind}
  j = json.dumps(msg, ensure_ascii=False).encode()
  header = struct.pack('=I', len(j))
  sys.stdout.buffer.write(header + j)
  sys.stdout.buffer.flush()

def setting_changed(ns, name, value):
  if ns == 'org.freedesktop.appearance' and name == 'color-scheme':
    handle_theme(value)

def main():
  DBusGMainLoop(set_as_default=True)

  bus = dbus.SessionBus()
  obj = bus.get_object('org.freedesktop.portal.Desktop', '/org/freedesktop/portal/desktop', follow_name_owner_changes=True)
  settings = dbus.Interface(obj, dbus_interface='org.freedesktop.portal.Settings')
  theme = settings.Read('org.freedesktop.appearance', 'color-scheme')
  handle_theme(theme)
  settings.connect_to_signal('SettingChanged', setting_changed)

  loop = GLib.MainLoop()
  try:
    loop.run()
  except KeyboardInterrupt:
    print()
    sys.exit(130)

if __name__ == '__main__':
  main()
